### ISSUE TITLE
Utils.hexToBytes - java.lang.StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by matthewgardner** [Scrin/RuuviCollector#21]
Been running for a few days - then this occured

```
2019-04-28 18:54:26.448 INFO  [Main] Successfully reading data from hcidump
2019-05-01 11:22:55.300 WARN  [Main] Uncaught exception while handling measurements from MAC address 
"C9B7EB45C0EF", if this repeats and this is not a Ruuvitag, consider blacklisting it
java.lang.StringIndexOutOfBoundsException: String index out of range: 19
	at java.lang.String.charAt(String.java:658)
	at fi.tkgwf.ruuvi.utils.Utils.hexToBytes(Utils.java:33)
	at fi.tkgwf.ruuvi.utils.HCIParser.readLine(HCIParser.java:51)
	at fi.tkgwf.ruuvi.Main.run(Main.java:104)
	at fi.tkgwf.ruuvi.Main.run(Main.java:80)
	at fi.tkgwf.ruuvi.Main.main(Main.java:43)
2019-05-01 11:22:55.330 DEBUG [Main] Offending line: device: disconnected
2019-05-01 11:22:55.342 INFO  [Main] Clean exit
```

I'm going to try and trap the error - then look at handling input - prefer the service to keep running and log the bad data. Thoughts?

**Comment by Scrin** [comment]
hcidump will print `device: disconnected` and exit gracefully if the bluetooth adapter is externally disabled or physically disconnected. However it is a bug that the collector will incorrectly try to parse this line and throw an StringIndexOutOfBoundsException.

The fact that the collector exits cleanly in this case is "working as intended", but now that I think about it, it's probably not the best behavior. However there is not much the collector can do in that case, as hcitool can't see or enable externally disabled devices
